### PR TITLE
Allow ts_sal to build in eups

### PR DESCRIPTION
**Pull request by rhiannonlynne**
The previous eupspkg.cfg.sh merged into ts_sal was buggy and did not work properly in many circumstances. This version has been more extensively debugged and does build successfully in lsstsw. The unit tests also actually run during the build process, which allows build errors to trigger failure messages appropriately.

### CODE REVIEW

**Comment by tribeiro** [comment]
@dmills-lsst, can you review this PR? Should this actually be merged to master as it is right now, or should it go to develop? 

There are some conflicting files reported so maybe @rhiannonlynne need to do a rebase? 

This seems like a great addition to the deployment system as we have report that it is possible to build all the topics simply using `scons` or `rebuild` on lsstsw...

**Comment by dmills-lsst** [comment]
The changes from this request have already been incorporated into ts_sal

**Comment by rhiannonlynne** [comment]
No, I don't believe so. This PR includes updates and improvements to the
merge that happened previously (assuming you mean the branch that I was
able to create a while ago on lsst-ts/ts_sal.).

This version of the build instructions has been tested with a full LSST
stack, and under a wider variety of conditions.

**Comment by rhiannonlynne** [comment]
Note that this PR also includes reference to the new test topic "Tests" and removes the topics which were not building (from the SUBSYSTEMS list).  That enables the unit test (which are now actually being run, but were left out of the previous build instructions in the older eupspkg.cfg.sh file) to pass properly. 

Other updates: 
the unit test is actually run during the build step, which allows jenkins to find the failing unit test
the library copying is more robust (it failed under some circumstances previously)
the LSST_LIBRARY_PATH is now set, as well as LD_LIBRARY_PATH : this is necessary for proper inclusion of the library path in the LSST build system

I just pulled the changes in master here back a branch of my fork of the repo and am running a build of sims_ocs using that branch. Once the build is successful, I will merge that branch into master which will automatically update here (so the merge conflicts should go away).

**Pull request merged**
