### PR TITLE
DM-18391: scons should only build Test and Script libraries if running tests

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by r-owen** [comment]
Another thing to try is "scons bin"; that should *not* build the Test or Script SALPY library (it will just copy a file from bin.src to bin). If that works then I think this is working for you.

**Comment by andrewbheyer** [comment]
> Another thing to try is "scons bin"; that should _not_ build the Test or Script SALPY library (it will just copy a file from bin.src to bin). If that works then I think this is working for you.
Testing this one now.

**Comment by andrewbheyer** [comment]
When running scons --clean git gets angry that some files are deleted,

```(opsim4) aheyer ~/py3-opsim/gitdir/ts_sal 03:12:39 [tickets/DM-18391] scons --clean
scons: Reading SConscript files ...
EUPS integration: enabled
Setting up environment to build package 'ts_sal'.
find . \( -name .svn -prune -o -name \* \) \( -name \*~ -o -name core -o -name \*.so -o -name \*.os -o -name \*.o -o -name \*.pyc -o -name \*.pkgc \) -exec rm -f {} \; ; rm -rf .sconf_temp .sconsign.dblite .sconsign.tmp config.log
Running pytest with 1 process
pytest: automated test discovery mode enabled.
scons: done reading SConscript files.
scons: Cleaning targets ...
Removed bin/make_salpy_libs.py
Removed python/lsst/ts/sal/version.py
Removed tests/.tests/pytest-ts_sal.xml-cov-ts_sal.xml
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/coverage_html.js
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/index.html
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/jquery.ba-throttle-debounce.min.js
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/jquery.hotkeys.js
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/jquery.isonscreen.js
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/jquery.min.js
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/jquery.tablesorter.min.js
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/keybd_closed.png
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/keybd_open.png
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/python_lsst_ts_sal_test_utils_py.html
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/status.json
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/style.css
Removed tests/.tests/pytest-ts_sal.xml-htmlcov/tests_test_sal_py.html
Removed directory tests/.tests/pytest-ts_sal.xml-htmlcov
Removed directory tests/.tests
scons: done cleaning targets.
(opsim4) aheyer ~/py3-opsim/gitdir/ts_sal 03:12:54 [tickets/DM-18391 x] git status
# On branch tickets/DM-18391
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	deleted:    lsstsal/lib/libtcl8.5.so
#	deleted:    lsstsal/lib/libthread2.6.5.so
#	deleted:    lsstsal/lib/libtile0.7.8.so
#	deleted:    lsstsal/lib/libtk8.5.so
#	deleted:    lsstsal/lib/thread2.6.5/libthread2.6.5.so
#	deleted:    lsstsal/lib/tile0.7.8/libtile0.7.8.so
#	deleted:    lsstsal/scripts/code/sample-generated/libshm_tcs_kernel_Target_server.so
#	deleted:    lsstsal/scripts/code/templates/boost.array.o
#	deleted:    lsstsal/scripts/code/templates/example.so
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEAppRecvThread.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEAppSendThread.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEDomain.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEDomainApp.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEDomainMgr.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEInit.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEMisc.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEPattern.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEPublication.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEPublicationTimer.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTESubscription.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEThreadUtils.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTETypeRegister.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ORTEVerbosity.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSAck.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSCSTReader.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSCSTReaderProc.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSCSTReaderTimer.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSCSTWriter.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSCSTWriterTimer.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSGap.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSHeader.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSHeardBeat.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSInfoDST.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSInfoREPLY.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSInfoSRC.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSInfoTS.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSIssue.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSPad.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSUtils.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-RTPSVar.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-cdr.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-conv.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-debug.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-event.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-fnmatch.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-htimerNtp.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-objectEntry.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-objectEntryTimer.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-objectUtils.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-parameter.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-sock.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ul_gavl.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/liborte/liborte_la-ul_gavlprim.o
#	deleted:    lsstsal/scripts/icd/orte-0.3.1/orte/manager/ortemanager.o
#	deleted:    lsstsal/scripts/lib/libxtcs.so
#
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by andrewbheyer** [comment]
scons bin seems to not build the libraries which is desired, here is the output I get 

```(opsim4) aheyer ~/py3-opsim/gitdir/ts_sal 03:12:21 [tickets/DM-18391] scons bin
scons: Reading SConscript files ...
EUPS integration: enabled
Checking who built the CC compiler...(cached) gcc=7.1.0
CC is gcc version 7.1.0
Checking for C++14 support
Checking whether the C++ compiler works... (cached) yes
C++14 supported with '-std=c++14'
Setting up environment to build package 'ts_sal'.
Running pytest with 1 process
pytest: automated test discovery mode enabled.
scons: done reading SConscript files.
scons: Building targets ...
scons: `bin' is up to date.
scons: done building targets.
```

**Comment by andrewbheyer** [comment]
When on develop and running `scons --clean` the libraries are being built. When on this branch and running `scons --clean` the libraries no longer are built and therefore the branch seems to be producing the desired effects.

**Comment by r-owen** [comment]
For the record the only thing `scons bin` does is copy *.py files from `bin.src/` to `bin/` and modify the #! line to point to a specific version of Python. It is not very interesting, but that's why it makes a good test of this ticket: it does very little and should not build the Test or Script SALPY libraries.

**Comment by r-owen** [comment]
Also regarding `scons --clean` deleting too much. Yes. I'm not sure how serious that is, but it is a bug. I suggest we file a different ticket to fix it, as that bug is pre-existing and unaffected by this ticket branch.

**Pull request merged**
