### PR TITLE
v4.0.0_RC2

### PR DESCRIPTION
**Pull request by dmills-lsst**
Roll up for release candidate 2

### CODE REVIEW

**Comment by dmills-lsst** [comment]
Rob is OOO, can you review this so we can merge.

**Comment by tribeiro** [comment]
who should review this Dave?

**Comment by andrewbheyer** [comment]
Sure thing Dave,

I had a task in review for Rob that I will be switching to you as well.

Thanks,

- Andrew

On Oct 25, 2019, at 1:25 PM, dmills-lsst <notifications@github.com<mailto:notifications@github.com>> wrote:


Rob is OOO, can you review this so we can merge.

**Comment by dmills-lsst** [comment]
Apparently Rob is in today, so whoever gets to it first.

**Pull request merged**
