### PR TITLE
DM-29927: make_idl_files: add --keep command-line argument

### PR DESCRIPTION
**Pull request by r-owen**
to keep all generated files.

### CODE REVIEW

**Comment by pkubanek** [comment]
Unfortunately that won't be that easy (I tried before, so I know it is not). Something still deletes <subsystem>/cpp, which is what I need for C++ compilation. After running make_idl_files.py MTM1M3:

```
*** Copy /home/petr/ts_sal/test/idl-templates/validated/sal/sal_revCoded_MTM1M3.idl to /home/petr/ts_idl/idl/sal_revCoded_MTM1M3.idl ***
*** Done generating MTM1M3 IDL file ***
[saluser@d8e745e08fa9 tests]$ ls $SAL_WORK_DIR/MTM1M3
isocpp  java  sal_revCoded_MTM1M3.idl
```

the cpp was there before (result of salgenerator sal cpp MTM1M3).

You can try with simpler schema (e.g. MTVMS), the steps required will be faster. I might look on what is causing the cpp deletion.

**Comment by pkubanek** [comment]
With MTVMS:

```
[saluser@d8e745e08fa9 tests]$ ls $SAL_WORK_DIR/MTVMS
cpp  isocpp  java
[saluser@d8e745e08fa9 tests]$ make_idl_files.py --keep MTVMS
Making IDL files for: MTVMS
$SAL_WORK_DIR = /home/petr/ts_sal/test
* Make MTVMS IDL file ***
*** Copy MTVMS XML files ***
*** Validate and generate MTVMS libraries ***
.......
SPL_HOME = /opt/OpenSpliceDDS/V6.9.0/HDE/x86_64.linux
OSPL_RELEASE = 6.9.190925OSS
*** Copy /home/petr/ts_sal/test/idl-templates/validated/sal/sal_revCoded_MTVMS.idl to /home/petr/ts_idl/idl/sal_revCoded_MTVMS.idl ***
*** Done generating MTVMS IDL file ***
[saluser@d8e745e08fa9 tests]$ ls $SAL_WORK_DIR/MTVMS
isocpp  java  sal_revCoded_MTVMS.idl
[saluser@d8e745e08fa9 tests]$ make_idl_files.py MTVMS
Making IDL files for: MTVMS
$SAL_WORK_DIR = /home/petr/ts_sal/test
* Make MTVMS IDL file ***
*** Copy MTVMS XML files ***
*** Validate and generate MTVMS libraries ***
.......
*** Copy /home/petr/ts_sal/test/idl-templates/validated/sal/sal_revCoded_MTVMS.idl to /home/petr/ts_idl/idl/sal_revCoded_MTVMS.idl ***
*** Cleanup MTVMS files ***
Remove /home/petr/ts_sal/test/MTVMS
Remove /home/petr/ts_sal/test/MTVMS_data
Remove /home/petr/ts_sal/test/idl-templates
Remove /home/petr/ts_sal/test/html
Remove /home/petr/ts_sal/test/include
Remove /home/petr/ts_sal/test/sql
*** Done generating MTVMS IDL file ***
[saluser@d8e745e08fa9 tests]$ ls $SAL_WORK_DIR/MTVMS
ls: cannot access /home/petr/ts_sal/test/MTVMS: No such file or directory`
```

so --keep helps a bit, but doesn't fix the problem I have.

**Comment by pkubanek** [comment]
This causes sal idl step to delete cpp folder:
```
diff --git a/bin/salgenerator b/bin/salgenerator
index b343d559..34b7ffe7 100755
--- a/bin/salgenerator
+++ b/bin/salgenerator
@@ -336,7 +336,6 @@ if { $OPTIONS(sal) } {
       if { $OPTIONS(verbose) } {stdlog $result}
     }
   } else {
-    exec rm -fr $SAL_WORK_DIR/[set base]/cpp
     exec cp $SAL_WORK_DIR/idl-templates/validated/sal/sal_revCoded_[set base].idl $SAL_WORK_DIR/[set base]/.
   }
   checkAssets $base
```

@dmills-lsst shall we commit this change as well?

**Review by pkubanek — APPROVED** [review]
Dave will move rm step at start of cpp generation. Please rebase & merge after that is done. Thanks

**Review by dmills-lsst — APPROVED** [review]
OK

**Comment by r-owen** [comment]
@dmills-lsst has merged his changes and I have rebased this ticket accordingly. It is ready to merge.

**Pull request merged**
