### PR TITLE
DM-22226: test new error handling

### PR DESCRIPTION
**Pull request by r-owen**
Including raising when strings are too long, data is null, or a topic has not been subscribed to.

### CODE REVIEW

**Comment by dmills-lsst** [comment]
Jenkins test fails on an Enum test

**Comment by r-owen** [comment]
I suspect Jenkins is running the wrong version of ts_xml. This needs 4.5.0 or later.

**Comment by r-owen** [comment]
@tribeiro kindly updated the version of ts_xml and the test is now passing. I also rebased it again for a recent change to davemills/DM-21983

**Comment by dmills-lsst** [comment]
Tests for 4.0/4.1 features

**Pull request merged**
